# Generated by Django 2.2.5 on 2019-09-30 14:04

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import testapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ('-name',),
                'default_permissions': (('view_author', 'Can see available Authors'),),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer')),
                ('information', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('image', image_cropping.fields.ImageCropField(blank=True, upload_to='media/customers')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('color', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'ordering': ('pk',),
                'default_permissions': (('view_customer', 'Can see available customers'),),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.BooleanField(help_text='Registered yet?', verbose_name='Registered')),
                ('sent', models.BooleanField(help_text='Invoice sent?', verbose_name='Sent')),
                ('paid', models.BooleanField(help_text='Invoice paid?', verbose_name='Paid')),
                ('date', models.DateTimeField(verbose_name='Creation date')),
                ('invoice_number', models.CharField(default=testapp.models.last_number, max_length=50, verbose_name='Invoice Number')),
                ('description1', models.TextField(blank=True, verbose_name='Description header')),
                ('description2', models.TextField(blank=True, verbose_name='Description footer')),
                ('subtotal', models.CharField(blank=True, help_text='Calculated field', max_length=200, verbose_name='Subtotal')),
                ('subtotal_iva', models.CharField(blank=True, help_text='Calculated field', max_length=200, verbose_name='Subtotal IVA')),
                ('subtotal_retentions', models.CharField(blank=True, help_text='Calculated field', max_length=200, verbose_name='Subtotal Retentions')),
                ('total', models.CharField(blank=True, help_text='Calculated field', max_length=200, verbose_name='Total')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='testapp.Customer')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ('pk',),
                'default_permissions': (('view_invoice', 'Can see available Invoices'),),
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, verbose_name='Reference')),
                ('concept', models.CharField(max_length=200, verbose_name='Concept')),
                ('quantity', models.CharField(max_length=200, verbose_name='Quantity')),
                ('unit', models.CharField(help_text='(days, hours...)', max_length=200, verbose_name='Unit')),
                ('unit_price', models.CharField(max_length=200, verbose_name='Unit Price')),
                ('amount', models.CharField(max_length=200, verbose_name='Ammount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line', to='testapp.Invoice')),
            ],
            options={
                'verbose_name': 'Line',
                'verbose_name_plural': 'Lines',
                'ordering': ('pk',),
                'default_permissions': (('view_line', 'Can see available lines'),),
            },
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, help_text='Active?', verbose_name='Status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='testapp.Author')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
